spring.application.name=api-gateway

server.port=8080


# Discovery Locator Configurations
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route 1: Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route 2: Workspace Service
spring.cloud.gateway.routes[1].id=workspace-service
spring.cloud.gateway.routes[1].uri=lb://WORKSPACE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/workspaces/**

# Route 3: Board Service
spring.cloud.gateway.routes[2].id=board-service
spring.cloud.gateway.routes[2].uri=lb://BOARD-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/boards/**

# Route 4: List Service
spring.cloud.gateway.routes[3].id=list-service
spring.cloud.gateway.routes[3].uri=lb://LIST-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/lists/**

# Route 5: Card Service
spring.cloud.gateway.routes[4].id=card-service
spring.cloud.gateway.routes[4].uri=lb://CARD-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/cards/**

# Route 6: Comment Service (Multiple Paths)
spring.cloud.gateway.routes[5].id=comment-service
spring.cloud.gateway.routes[5].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/comments/**,/attachments/**

# Route 7: Label Service (Multiple Paths)
spring.cloud.gateway.routes[6].id=label-service
spring.cloud.gateway.routes[6].uri=lb://LABEL-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/labels/**,/checklists/**

# Route 8: Notification Service
spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/notifications/**

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Actuator Management Endpoints
management.endpoints.web.exposure.include=health,info
