spring.application.name=config-server

server.port=8888

# Git Repository URL (Points to the repository, not individual files)
spring.cloud.config.server.git.uri=https://github.com/rahul-kumar-3/flowboard-config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true